AllCops:
  Exclude:
    - "**/vendor/**/*"
    - "**/*.gemspec"
    - "spec/**"
  NewCops: enable
  TargetRubyVersion: 3.0.1
  SuggestExtensions: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Enabled: false

Style/AsciiComments:
  Enabled: false
